Python 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)] on win32
Enter "help" below or click "Help" above for more information.

= RESTART: C:/Users/asnat/AppData/Local/Programs/Python/Python313/math module.py
Help on module keyword:

NAME
    keyword - Keywords (from "Grammar/python.gram")

MODULE REFERENCE
    https://docs.python.org/3.13/library/keyword.html

    The following documentation is automatically generated from the Python
    source files.  It may be incomplete, incorrect or include features that
    are considered implementation detail and may vary between Python
    implementations.  When in doubt, consult the module reference at the
    location listed above.

DESCRIPTION
    This file is automatically generated; please don't muck it up!

    To update the symbols in this file, 'cd' to the top directory of
    the python source tree and run:

        PYTHONPATH=Tools/peg_generator python3 -m pegen.keywordgen         Grammar/python.gram         Grammar/Tokens         Lib/keyword.py

    Alternatively, you can run 'make regen-keyword'.

FUNCTIONS
    iskeyword = __contains__(object, /) method of builtins.frozenset instance
        x.__contains__(y) <==> y in x.

    issoftkeyword = __contains__(object, /) method of builtins.frozenset instance
        x.__contains__(y) <==> y in x.

DATA
    __all__ = ['iskeyword', 'issoftkeyword', 'kwlist', 'softkwlist']
    kwlist = ['False', 'None', 'True', 'and', 'as', 'assert', 'async', 'aw...
    softkwlist = ['_', 'case', 'match', 'type']

FILE
    c:\users\asnat\appdata\local\programs\python\python313\lib\keyword.py


None

= RESTART: C:/Users/asnat/AppData/Local/Programs/Python/Python313/math module.py

Here is a list of the Python keywords.  Enter any keyword to get more help.

False               class               from                or
None                continue            global              pass
True                def                 if                  raise
and                 del                 import              return
as                  elif                in                  try
assert              else                is                  while
async               except              lambda              with
await               finally             nonlocal            yield
break               for                 not                 

None

= RESTART: C:/Users/asnat/AppData/Local/Programs/Python/Python313/math module.py

Here is a list of the Python keywords.  Enter any keyword to get more help.

False               class               from                or
None                continue            global              pass
True                def                 if                  raise
and                 del                 import              return
as                  elif                in                  try
assert              else                is                  while
async               except              lambda              with
await               finally             nonlocal            yield
break               for                 not                 

None
Help on built-in module math:

NAME
    math

DESCRIPTION
    This module provides access to the mathematical functions
    defined by the C standard.

FUNCTIONS
    acos(x, /)
        Return the arc cosine (measured in radians) of x.

        The result is between 0 and pi.

    acosh(x, /)
        Return the inverse hyperbolic cosine of x.

    asin(x, /)
        Return the arc sine (measured in radians) of x.

        The result is between -pi/2 and pi/2.

    asinh(x, /)
        Return the inverse hyperbolic sine of x.

    atan(x, /)
        Return the arc tangent (measured in radians) of x.

        The result is between -pi/2 and pi/2.

    atan2(y, x, /)
        Return the arc tangent (measured in radians) of y/x.

        Unlike atan(y/x), the signs of both x and y are considered.

    atanh(x, /)
        Return the inverse hyperbolic tangent of x.

    cbrt(x, /)
        Return the cube root of x.

    ceil(x, /)
        Return the ceiling of x as an Integral.

        This is the smallest integer >= x.

    comb(n, k, /)
        Number of ways to choose k items from n items without repetition and without order.

        Evaluates to n! / (k! * (n - k)!) when k <= n and evaluates
        to zero when k > n.

        Also called the binomial coefficient because it is equivalent
        to the coefficient of k-th term in polynomial expansion of the
        expression (1 + x)**n.

        Raises TypeError if either of the arguments are not integers.
        Raises ValueError if either of the arguments are negative.

    copysign(x, y, /)
        Return a float with the magnitude (absolute value) of x but the sign of y.

        On platforms that support signed zeros, copysign(1.0, -0.0)
        returns -1.0.

    cos(x, /)
        Return the cosine of x (measured in radians).

    cosh(x, /)
        Return the hyperbolic cosine of x.

    degrees(x, /)
        Convert angle x from radians to degrees.

    dist(p, q, /)
        Return the Euclidean distance between two points p and q.

        The points should be specified as sequences (or iterables) of
        coordinates.  Both inputs must have the same dimension.

        Roughly equivalent to:
            sqrt(sum((px - qx) ** 2.0 for px, qx in zip(p, q)))

    erf(x, /)
        Error function at x.

    erfc(x, /)
        Complementary error function at x.

    exp(x, /)
        Return e raised to the power of x.

    exp2(x, /)
        Return 2 raised to the power of x.

    expm1(x, /)
        Return exp(x)-1.

        This function avoids the loss of precision involved in the direct evaluation of exp(x)-1 for small x.

    fabs(x, /)
        Return the absolute value of the float x.

    factorial(n, /)
        Find n!.

        Raise a ValueError if x is negative or non-integral.

    floor(x, /)
        Return the floor of x as an Integral.

        This is the largest integer <= x.

    fma(x, y, z, /)
        Fused multiply-add operation.

        Compute (x * y) + z with a single round.

    fmod(x, y, /)
        Return fmod(x, y), according to platform C.

        x % y may differ.

    frexp(x, /)
        Return the mantissa and exponent of x, as pair (m, e).

        m is a float and e is an int, such that x = m * 2.**e.
        If x is 0, m and e are both 0.  Else 0.5 <= abs(m) < 1.0.

    fsum(seq, /)
        Return an accurate floating-point sum of values in the iterable seq.

        Assumes IEEE-754 floating-point arithmetic.

    gamma(x, /)
        Gamma function at x.

    gcd(*integers)
        Greatest Common Divisor.

    hypot(...)
        hypot(*coordinates) -> value

        Multidimensional Euclidean distance from the origin to a point.

        Roughly equivalent to:
            sqrt(sum(x**2 for x in coordinates))

        For a two dimensional point (x, y), gives the hypotenuse
        using the Pythagorean theorem:  sqrt(x*x + y*y).

        For example, the hypotenuse of a 3/4/5 right triangle is:

            >>> hypot(3.0, 4.0)
            5.0

    isclose(a, b, *, rel_tol=1e-09, abs_tol=0.0)
        Determine whether two floating-point numbers are close in value.

          rel_tol
            maximum difference for being considered "close", relative to the
            magnitude of the input values
          abs_tol
            maximum difference for being considered "close", regardless of the
            magnitude of the input values

        Return True if a is close in value to b, and False otherwise.

        For the values to be considered close, the difference between them
        must be smaller than at least one of the tolerances.

        -inf, inf and NaN behave similarly to the IEEE 754 Standard.  That
        is, NaN is not close to anything, even itself.  inf and -inf are
        only close to themselves.

    isfinite(x, /)
        Return True if x is neither an infinity nor a NaN, and False otherwise.

    isinf(x, /)
        Return True if x is a positive or negative infinity, and False otherwise.

    isnan(x, /)
        Return True if x is a NaN (not a number), and False otherwise.

    isqrt(n, /)
        Return the integer part of the square root of the input.

    lcm(*integers)
        Least Common Multiple.

    ldexp(x, i, /)
        Return x * (2**i).

        This is essentially the inverse of frexp().

    lgamma(x, /)
        Natural logarithm of absolute value of Gamma function at x.

    log(...)
        log(x, [base=math.e])
        Return the logarithm of x to the given base.

        If the base is not specified, returns the natural logarithm (base e) of x.

    log10(x, /)
        Return the base 10 logarithm of x.

    log1p(x, /)
        Return the natural logarithm of 1+x (base e).

        The result is computed in a way which is accurate for x near zero.

    log2(x, /)
        Return the base 2 logarithm of x.

    modf(x, /)
        Return the fractional and integer parts of x.

        Both results carry the sign of x and are floats.

    nextafter(x, y, /, *, steps=None)
        Return the floating-point value the given number of steps after x towards y.

        If steps is not specified or is None, it defaults to 1.

        Raises a TypeError, if x or y is not a double, or if steps is not an integer.
        Raises ValueError if steps is negative.

    perm(n, k=None, /)
        Number of ways to choose k items from n items without repetition and with order.

        Evaluates to n! / (n - k)! when k <= n and evaluates
        to zero when k > n.

        If k is not specified or is None, then k defaults to n
        and the function returns n!.

        Raises TypeError if either of the arguments are not integers.
        Raises ValueError if either of the arguments are negative.

    pow(x, y, /)
        Return x**y (x to the power of y).

    prod(iterable, /, *, start=1)
        Calculate the product of all the elements in the input iterable.

        The default start value for the product is 1.

        When the iterable is empty, return the start value.  This function is
        intended specifically for use with numeric values and may reject
        non-numeric types.

    radians(x, /)
        Convert angle x from degrees to radians.

    remainder(x, y, /)
        Difference between x and the closest integer multiple of y.

        Return x - n*y where n*y is the closest integer multiple of y.
        In the case where x is exactly halfway between two multiples of
        y, the nearest even value of n is used. The result is always exact.

    sin(x, /)
        Return the sine of x (measured in radians).

    sinh(x, /)
        Return the hyperbolic sine of x.

    sqrt(x, /)
        Return the square root of x.

    sumprod(p, q, /)
        Return the sum of products of values from two iterables p and q.

        Roughly equivalent to:

            sum(itertools.starmap(operator.mul, zip(p, q, strict=True)))

        For float and mixed int/float inputs, the intermediate products
        and sums are computed with extended precision.

    tan(x, /)
        Return the tangent of x (measured in radians).

    tanh(x, /)
        Return the hyperbolic tangent of x.

    trunc(x, /)
        Truncates the Real x to the nearest Integral toward 0.

        Uses the __trunc__ magic method.

    ulp(x, /)
        Return the value of the least significant bit of the float x.

DATA
    e = 2.718281828459045
    inf = inf
    nan = nan
    pi = 3.141592653589793
    tau = 6.283185307179586

FILE
    (built-in)


None

= RESTART: C:/Users/asnat/AppData/Local/Programs/Python/Python313/math module.py

Here is a list of the Python keywords.  Enter any keyword to get more help.

False               class               from                or
None                continue            global              pass
True                def                 if                  raise
and                 del                 import              return
as                  elif                in                  try
assert              else                is                  while
async               except              lambda              with
await               finally             nonlocal            yield
break               for                 not                 

None

None
Traceback (most recent call last):
  File "C:/Users/asnat/AppData/Local/Programs/Python/Python313/math module.py", line 7, in <module>
    print(math,sqrt(81))
NameError: name 'sqrt' is not defined

= RESTART: C:/Users/asnat/AppData/Local/Programs/Python/Python313/math module.py

Here is a list of the Python keywords.  Enter any keyword to get more help.

False               class               from                or
None                continue            global              pass
True                def                 if                  raise
and                 del                 import              return
as                  elif                in                  try
assert              else                is                  while
async               except              lambda              with
await               finally             nonlocal            yield
break               for                 not                 

None

None
9.0

= RESTART: C:/Users/asnat/AppData/Local/Programs/Python/Python313/math module.py
enter the number:5
factorial of5is 120

= RESTART: C:/Users/asnat/AppData/Local/Programs/Python/Python313/math module.py
46
45

= RESTART: C:/Users/asnat/AppData/Local/Programs/Python/Python313/math module.py
46
45
remainder value is" 1.0
Traceback (most recent call last):
  File "C:/Users/asnat/AppData/Local/Programs/Python/Python313/math module.py", line 26, in <module>
    print('GCD is:'.gcd(24,12))
AttributeError: 'str' object has no attribute 'gcd'

= RESTART: C:/Users/asnat/AppData/Local/Programs/Python/Python313/math module.py
46
45
remainder value is" 1.0
GCD is: 12

= RESTART: C:/Users/asnat/AppData/Local/Programs/Python/Python313/math module.py
46
45
remainder value is" 1.0
GCD is: 12
sum of values is: 100.0

= RESTART: C:/Users/asnat/AppData/Local/Programs/Python/Python313/math module.py
46
45
remainder value is" 1.0
GCD is: 12
sum of values is: 100.0
sine value is= 0.0
cosine value is= 1.0
tan value is= 0.0

==== RESTART: C:/Users/asnat/AppData/Local/Programs/Python/Python313/math module.py ====
46
45
remainder value is" 1.0
GCD is: 12
1.791759469228055
3.58351893845611
6.907755278982137

==== RESTART: C:/Users/asnat/AppData/Local/Programs/Python/Python313/math module.py ====
46
45
remainder value is" 1.0
GCD is: 12
pi value is= 3.141592653589793
euler value is= 2.718281828459045
tau value is= 6.283185307179586

==== RESTART: C:/Users/asnat/AppData/Local/Programs/Python/Python313/math module.py ====
46
45
remainder value is" 1.0
GCD is: 12
not a number= nan
infinity= inf

==== RESTART: C:/Users/asnat/AppData/Local/Programs/Python/Python313/math module.py ====
46
45
remainder value is" 1.0
GCD is: 12
not a number= nan
infinity= inf
(7+0j)

==== RESTART: C:/Users/asnat/AppData/Local/Programs/Python/Python313/math module.py ====
46
45
remainder value is" 1.0
GCD is: 12
                                  2025

      January                   February                   March
Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su
       1  2  3  4  5                      1  2                      1  2
 6  7  8  9 10 11 12       3  4  5  6  7  8  9       3  4  5  6  7  8  9
13 14 15 16 17 18 19      10 11 12 13 14 15 16      10 11 12 13 14 15 16
20 21 22 23 24 25 26      17 18 19 20 21 22 23      17 18 19 20 21 22 23
27 28 29 30 31            24 25 26 27 28            24 25 26 27 28 29 30
                                                    31

       April                      May                       June
Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su
    1  2  3  4  5  6                1  2  3  4                         1
 7  8  9 10 11 12 13       5  6  7  8  9 10 11       2  3  4  5  6  7  8
14 15 16 17 18 19 20      12 13 14 15 16 17 18       9 10 11 12 13 14 15
21 22 23 24 25 26 27      19 20 21 22 23 24 25      16 17 18 19 20 21 22
28 29 30                  26 27 28 29 30 31         23 24 25 26 27 28 29
                                                    30

        July                     August                  September
Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su
    1  2  3  4  5  6                   1  2  3       1  2  3  4  5  6  7
 7  8  9 10 11 12 13       4  5  6  7  8  9 10       8  9 10 11 12 13 14
14 15 16 17 18 19 20      11 12 13 14 15 16 17      15 16 17 18 19 20 21
21 22 23 24 25 26 27      18 19 20 21 22 23 24      22 23 24 25 26 27 28
28 29 30 31               25 26 27 28 29 30 31      29 30

      October                   November                  December
Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su
       1  2  3  4  5                      1  2       1  2  3  4  5  6  7
 6  7  8  9 10 11 12       3  4  5  6  7  8  9       8  9 10 11 12 13 14
13 14 15 16 17 18 19      10 11 12 13 14 15 16      15 16 17 18 19 20 21
20 21 22 23 24 25 26      17 18 19 20 21 22 23      22 23 24 25 26 27 28
27 28 29 30 31            24 25 26 27 28 29 30      29 30 31


==== RESTART: C:/Users/asnat/AppData/Local/Programs/Python/Python313/math module.py ====
46
45
remainder value is" 1.0
GCD is: 12
                                  2025

      January                   February                   March
Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su
       1  2  3  4  5                      1  2                      1  2
 6  7  8  9 10 11 12       3  4  5  6  7  8  9       3  4  5  6  7  8  9
13 14 15 16 17 18 19      10 11 12 13 14 15 16      10 11 12 13 14 15 16
20 21 22 23 24 25 26      17 18 19 20 21 22 23      17 18 19 20 21 22 23
27 28 29 30 31            24 25 26 27 28            24 25 26 27 28 29 30
                                                    31

       April                      May                       June
Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su
    1  2  3  4  5  6                1  2  3  4                         1
 7  8  9 10 11 12 13       5  6  7  8  9 10 11       2  3  4  5  6  7  8
14 15 16 17 18 19 20      12 13 14 15 16 17 18       9 10 11 12 13 14 15
21 22 23 24 25 26 27      19 20 21 22 23 24 25      16 17 18 19 20 21 22
28 29 30                  26 27 28 29 30 31         23 24 25 26 27 28 29
                                                    30

        July                     August                  September
Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su
    1  2  3  4  5  6                   1  2  3       1  2  3  4  5  6  7
 7  8  9 10 11 12 13       4  5  6  7  8  9 10       8  9 10 11 12 13 14
14 15 16 17 18 19 20      11 12 13 14 15 16 17      15 16 17 18 19 20 21
21 22 23 24 25 26 27      18 19 20 21 22 23 24      22 23 24 25 26 27 28
28 29 30 31               25 26 27 28 29 30 31      29 30

      October                   November                  December
Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su
       1  2  3  4  5                      1  2       1  2  3  4  5  6  7
 6  7  8  9 10 11 12       3  4  5  6  7  8  9       8  9 10 11 12 13 14
13 14 15 16 17 18 19      10 11 12 13 14 15 16      15 16 17 18 19 20 21
20 21 22 23 24 25 26      17 18 19 20 21 22 23      22 23 24 25 26 27 28
27 28 29 30 31            24 25 26 27 28 29 30      29 30 31

                                  2050

      January                   February                   March
Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su
                1  2          1  2  3  4  5  6          1  2  3  4  5  6
 3  4  5  6  7  8  9       7  8  9 10 11 12 13       7  8  9 10 11 12 13
10 11 12 13 14 15 16      14 15 16 17 18 19 20      14 15 16 17 18 19 20
17 18 19 20 21 22 23      21 22 23 24 25 26 27      21 22 23 24 25 26 27
24 25 26 27 28 29 30      28                        28 29 30 31
31

       April                      May                       June
Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su
             1  2  3                         1             1  2  3  4  5
 4  5  6  7  8  9 10       2  3  4  5  6  7  8       6  7  8  9 10 11 12
11 12 13 14 15 16 17       9 10 11 12 13 14 15      13 14 15 16 17 18 19
18 19 20 21 22 23 24      16 17 18 19 20 21 22      20 21 22 23 24 25 26
25 26 27 28 29 30         23 24 25 26 27 28 29      27 28 29 30
                          30 31

        July                     August                  September
Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su
             1  2  3       1  2  3  4  5  6  7                1  2  3  4
 4  5  6  7  8  9 10       8  9 10 11 12 13 14       5  6  7  8  9 10 11
11 12 13 14 15 16 17      15 16 17 18 19 20 21      12 13 14 15 16 17 18
18 19 20 21 22 23 24      22 23 24 25 26 27 28      19 20 21 22 23 24 25
25 26 27 28 29 30 31      29 30 31                  26 27 28 29 30

      October                   November                  December
Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su
                1  2          1  2  3  4  5  6                1  2  3  4
 3  4  5  6  7  8  9       7  8  9 10 11 12 13       5  6  7  8  9 10 11
10 11 12 13 14 15 16      14 15 16 17 18 19 20      12 13 14 15 16 17 18
17 18 19 20 21 22 23      21 22 23 24 25 26 27      19 20 21 22 23 24 25
24 25 26 27 28 29 30      28 29 30                  26 27 28 29 30 31
31


==== RESTART: C:/Users/asnat/AppData/Local/Programs/Python/Python313/math module.py ====
46
45
remainder value is" 1.0
GCD is: 12
enter the year:2027
Traceback (most recent call last):
  File "C:/Users/asnat/AppData/Local/Programs/Python/Python313/math module.py", line 72, in <module>
    print(cal,calendar(year))
NameError: name 'calendar' is not defined. Did you forget to import 'calendar'?

==== RESTART: C:/Users/asnat/AppData/Local/Programs/Python/Python313/math module.py ====
46
45
remainder value is" 1.0
GCD is: 12
enter the year:2020
                                  2020

      January                   February                   March
Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su
       1  2  3  4  5                      1  2                         1
 6  7  8  9 10 11 12       3  4  5  6  7  8  9       2  3  4  5  6  7  8
13 14 15 16 17 18 19      10 11 12 13 14 15 16       9 10 11 12 13 14 15
20 21 22 23 24 25 26      17 18 19 20 21 22 23      16 17 18 19 20 21 22
27 28 29 30 31            24 25 26 27 28 29         23 24 25 26 27 28 29
                                                    30 31

       April                      May                       June
Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su
       1  2  3  4  5                   1  2  3       1  2  3  4  5  6  7
 6  7  8  9 10 11 12       4  5  6  7  8  9 10       8  9 10 11 12 13 14
13 14 15 16 17 18 19      11 12 13 14 15 16 17      15 16 17 18 19 20 21
20 21 22 23 24 25 26      18 19 20 21 22 23 24      22 23 24 25 26 27 28
27 28 29 30               25 26 27 28 29 30 31      29 30

        July                     August                  September
Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su
       1  2  3  4  5                      1  2          1  2  3  4  5  6
 6  7  8  9 10 11 12       3  4  5  6  7  8  9       7  8  9 10 11 12 13
13 14 15 16 17 18 19      10 11 12 13 14 15 16      14 15 16 17 18 19 20
20 21 22 23 24 25 26      17 18 19 20 21 22 23      21 22 23 24 25 26 27
27 28 29 30 31            24 25 26 27 28 29 30      28 29 30
                          31

      October                   November                  December
Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su
          1  2  3  4                         1          1  2  3  4  5  6
 5  6  7  8  9 10 11       2  3  4  5  6  7  8       7  8  9 10 11 12 13
12 13 14 15 16 17 18       9 10 11 12 13 14 15      14 15 16 17 18 19 20
19 20 21 22 23 24 25      16 17 18 19 20 21 22      21 22 23 24 25 26 27
26 27 28 29 30 31         23 24 25 26 27 28 29      28 29 30 31
                          30


==== RESTART: C:/Users/asnat/AppData/Local/Programs/Python/Python313/math module.py ====
46
45
remainder value is" 1.0
GCD is: 12
enter the year=2023
enter the month=6
     June 2023
Mo Tu We Th Fr Sa Su
          1  2  3  4
 5  6  7  8  9 10 11
12 13 14 15 16 17 18
19 20 21 22 23 24 25
26 27 28 29 30


==== RESTART: C:/Users/asnat/AppData/Local/Programs/Python/Python313/math module.py ====
46
45
remainder value is" 1.0
GCD is: 12
enter the year=2026
Traceback (most recent call last):
  File "C:/Users/asnat/AppData/Local/Programs/Python/Python313/math module.py", line 86, in <module>
    if(cal.isleap(y)):
NameError: name 'cal' is not defined

==== RESTART: C:/Users/asnat/AppData/Local/Programs/Python/Python313/math module.py ====
46
45
remainder value is" 1.0
GCD is: 12
enter the year=2026
2026 is not a leap year

==== RESTART: C:/Users/asnat/AppData/Local/Programs/Python/Python313/math module.py ====
46
45
remainder value is" 1.0
GCD is: 12
pi value is= 3.141592653589793
euler value is= 2.718281828459045
tau value is= 6.283185307179586
not a number= nan
infinity= inf
(7+0j)
                                  2025

      January                   February                   March
Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su
       1  2  3  4  5                      1  2                      1  2
 6  7  8  9 10 11 12       3  4  5  6  7  8  9       3  4  5  6  7  8  9
13 14 15 16 17 18 19      10 11 12 13 14 15 16      10 11 12 13 14 15 16
20 21 22 23 24 25 26      17 18 19 20 21 22 23      17 18 19 20 21 22 23
27 28 29 30 31            24 25 26 27 28            24 25 26 27 28 29 30
                                                    31

       April                      May                       June
Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su
    1  2  3  4  5  6                1  2  3  4                         1
 7  8  9 10 11 12 13       5  6  7  8  9 10 11       2  3  4  5  6  7  8
14 15 16 17 18 19 20      12 13 14 15 16 17 18       9 10 11 12 13 14 15
21 22 23 24 25 26 27      19 20 21 22 23 24 25      16 17 18 19 20 21 22
28 29 30                  26 27 28 29 30 31         23 24 25 26 27 28 29
                                                    30

        July                     August                  September
Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su
    1  2  3  4  5  6                   1  2  3       1  2  3  4  5  6  7
 7  8  9 10 11 12 13       4  5  6  7  8  9 10       8  9 10 11 12 13 14
14 15 16 17 18 19 20      11 12 13 14 15 16 17      15 16 17 18 19 20 21
21 22 23 24 25 26 27      18 19 20 21 22 23 24      22 23 24 25 26 27 28
28 29 30 31               25 26 27 28 29 30 31      29 30

      October                   November                  December
Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su
       1  2  3  4  5                      1  2       1  2  3  4  5  6  7
 6  7  8  9 10 11 12       3  4  5  6  7  8  9       8  9 10 11 12 13 14
13 14 15 16 17 18 19      10 11 12 13 14 15 16      15 16 17 18 19 20 21
20 21 22 23 24 25 26      17 18 19 20 21 22 23      22 23 24 25 26 27 28
27 28 29 30 31            24 25 26 27 28 29 30      29 30 31

                                  2050

      January                   February                   March
Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su
                1  2          1  2  3  4  5  6          1  2  3  4  5  6
 3  4  5  6  7  8  9       7  8  9 10 11 12 13       7  8  9 10 11 12 13
10 11 12 13 14 15 16      14 15 16 17 18 19 20      14 15 16 17 18 19 20
17 18 19 20 21 22 23      21 22 23 24 25 26 27      21 22 23 24 25 26 27
24 25 26 27 28 29 30      28                        28 29 30 31
31

       April                      May                       June
Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su
             1  2  3                         1             1  2  3  4  5
 4  5  6  7  8  9 10       2  3  4  5  6  7  8       6  7  8  9 10 11 12
11 12 13 14 15 16 17       9 10 11 12 13 14 15      13 14 15 16 17 18 19
18 19 20 21 22 23 24      16 17 18 19 20 21 22      20 21 22 23 24 25 26
25 26 27 28 29 30         23 24 25 26 27 28 29      27 28 29 30
                          30 31

        July                     August                  September
Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su
             1  2  3       1  2  3  4  5  6  7                1  2  3  4
 4  5  6  7  8  9 10       8  9 10 11 12 13 14       5  6  7  8  9 10 11
11 12 13 14 15 16 17      15 16 17 18 19 20 21      12 13 14 15 16 17 18
18 19 20 21 22 23 24      22 23 24 25 26 27 28      19 20 21 22 23 24 25
25 26 27 28 29 30 31      29 30 31                  26 27 28 29 30

      October                   November                  December
Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su
                1  2          1  2  3  4  5  6                1  2  3  4
 3  4  5  6  7  8  9       7  8  9 10 11 12 13       5  6  7  8  9 10 11
10 11 12 13 14 15 16      14 15 16 17 18 19 20      12 13 14 15 16 17 18
17 18 19 20 21 22 23      21 22 23 24 25 26 27      19 20 21 22 23 24 25
24 25 26 27 28 29 30      28 29 30                  26 27 28 29 30 31
31

enter the year:2023
                                  2023

      January                   February                   March
Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su
                   1             1  2  3  4  5             1  2  3  4  5
 2  3  4  5  6  7  8       6  7  8  9 10 11 12       6  7  8  9 10 11 12
 9 10 11 12 13 14 15      13 14 15 16 17 18 19      13 14 15 16 17 18 19
16 17 18 19 20 21 22      20 21 22 23 24 25 26      20 21 22 23 24 25 26
23 24 25 26 27 28 29      27 28                     27 28 29 30 31
30 31

       April                      May                       June
Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su
                1  2       1  2  3  4  5  6  7                1  2  3  4
 3  4  5  6  7  8  9       8  9 10 11 12 13 14       5  6  7  8  9 10 11
10 11 12 13 14 15 16      15 16 17 18 19 20 21      12 13 14 15 16 17 18
17 18 19 20 21 22 23      22 23 24 25 26 27 28      19 20 21 22 23 24 25
24 25 26 27 28 29 30      29 30 31                  26 27 28 29 30

        July                     August                  September
Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su
                1  2          1  2  3  4  5  6                   1  2  3
 3  4  5  6  7  8  9       7  8  9 10 11 12 13       4  5  6  7  8  9 10
10 11 12 13 14 15 16      14 15 16 17 18 19 20      11 12 13 14 15 16 17
17 18 19 20 21 22 23      21 22 23 24 25 26 27      18 19 20 21 22 23 24
24 25 26 27 28 29 30      28 29 30 31               25 26 27 28 29 30
31

      October                   November                  December
Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su
                   1             1  2  3  4  5                   1  2  3
 2  3  4  5  6  7  8       6  7  8  9 10 11 12       4  5  6  7  8  9 10
 9 10 11 12 13 14 15      13 14 15 16 17 18 19      11 12 13 14 15 16 17
16 17 18 19 20 21 22      20 21 22 23 24 25 26      18 19 20 21 22 23 24
23 24 25 26 27 28 29      27 28 29 30               25 26 27 28 29 30 31
30 31

enter the year=2023
enter the month=3
     March 2023
Mo Tu We Th Fr Sa Su
       1  2  3  4  5
 6  7  8  9 10 11 12
13 14 15 16 17 18 19
20 21 22 23 24 25 26
27 28 29 30 31

2025-05-21 12:11:35.098731

==== RESTART: C:/Users/asnat/AppData/Local/Programs/Python/Python313/math module.py ====
46
45
remainder value is" 1.0
GCD is: 12
pi value is= 3.141592653589793
euler value is= 2.718281828459045
tau value is= 6.283185307179586
not a number= nan
infinity= inf
(7+0j)
                                  2025

      January                   February                   March
Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su
       1  2  3  4  5                      1  2                      1  2
 6  7  8  9 10 11 12       3  4  5  6  7  8  9       3  4  5  6  7  8  9
13 14 15 16 17 18 19      10 11 12 13 14 15 16      10 11 12 13 14 15 16
20 21 22 23 24 25 26      17 18 19 20 21 22 23      17 18 19 20 21 22 23
27 28 29 30 31            24 25 26 27 28            24 25 26 27 28 29 30
                                                    31

       April                      May                       June
Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su
    1  2  3  4  5  6                1  2  3  4                         1
 7  8  9 10 11 12 13       5  6  7  8  9 10 11       2  3  4  5  6  7  8
14 15 16 17 18 19 20      12 13 14 15 16 17 18       9 10 11 12 13 14 15
21 22 23 24 25 26 27      19 20 21 22 23 24 25      16 17 18 19 20 21 22
28 29 30                  26 27 28 29 30 31         23 24 25 26 27 28 29
                                                    30

        July                     August                  September
Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su
    1  2  3  4  5  6                   1  2  3       1  2  3  4  5  6  7
 7  8  9 10 11 12 13       4  5  6  7  8  9 10       8  9 10 11 12 13 14
14 15 16 17 18 19 20      11 12 13 14 15 16 17      15 16 17 18 19 20 21
21 22 23 24 25 26 27      18 19 20 21 22 23 24      22 23 24 25 26 27 28
28 29 30 31               25 26 27 28 29 30 31      29 30

      October                   November                  December
Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su
       1  2  3  4  5                      1  2       1  2  3  4  5  6  7
 6  7  8  9 10 11 12       3  4  5  6  7  8  9       8  9 10 11 12 13 14
13 14 15 16 17 18 19      10 11 12 13 14 15 16      15 16 17 18 19 20 21
20 21 22 23 24 25 26      17 18 19 20 21 22 23      22 23 24 25 26 27 28
27 28 29 30 31            24 25 26 27 28 29 30      29 30 31

                                  2050

      January                   February                   March
Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su
                1  2          1  2  3  4  5  6          1  2  3  4  5  6
 3  4  5  6  7  8  9       7  8  9 10 11 12 13       7  8  9 10 11 12 13
10 11 12 13 14 15 16      14 15 16 17 18 19 20      14 15 16 17 18 19 20
17 18 19 20 21 22 23      21 22 23 24 25 26 27      21 22 23 24 25 26 27
24 25 26 27 28 29 30      28                        28 29 30 31
31

       April                      May                       June
Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su
             1  2  3                         1             1  2  3  4  5
 4  5  6  7  8  9 10       2  3  4  5  6  7  8       6  7  8  9 10 11 12
11 12 13 14 15 16 17       9 10 11 12 13 14 15      13 14 15 16 17 18 19
18 19 20 21 22 23 24      16 17 18 19 20 21 22      20 21 22 23 24 25 26
25 26 27 28 29 30         23 24 25 26 27 28 29      27 28 29 30
                          30 31

        July                     August                  September
Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su
             1  2  3       1  2  3  4  5  6  7                1  2  3  4
 4  5  6  7  8  9 10       8  9 10 11 12 13 14       5  6  7  8  9 10 11
11 12 13 14 15 16 17      15 16 17 18 19 20 21      12 13 14 15 16 17 18
18 19 20 21 22 23 24      22 23 24 25 26 27 28      19 20 21 22 23 24 25
25 26 27 28 29 30 31      29 30 31                  26 27 28 29 30

      October                   November                  December
Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su
                1  2          1  2  3  4  5  6                1  2  3  4
 3  4  5  6  7  8  9       7  8  9 10 11 12 13       5  6  7  8  9 10 11
10 11 12 13 14 15 16      14 15 16 17 18 19 20      12 13 14 15 16 17 18
17 18 19 20 21 22 23      21 22 23 24 25 26 27      19 20 21 22 23 24 25
24 25 26 27 28 29 30      28 29 30                  26 27 28 29 30 31
31

enter the year:
==== RESTART: C:/Users/asnat/AppData/Local/Programs/Python/Python313/math module.py ====
46
45
remainder value is" 1.0
GCD is: 12
2025-05-21

==== RESTART: C:/Users/asnat/AppData/Local/Programs/Python/Python313/math module.py ====
46
45
remainder value is" 1.0
GCD is: 12
Traceback (most recent call last):
  File "C:/Users/asnat/AppData/Local/Programs/Python/Python313/math module.py", line 103, in <module>
    print('current time:',dt.strftime('%H/%M/%S'))
NameError: name 'dt' is not defined

==== RESTART: C:/Users/asnat/AppData/Local/Programs/Python/Python313/math module.py ====
46
45
remainder value is" 1.0
GCD is: 12
Traceback (most recent call last):
  File "C:/Users/asnat/AppData/Local/Programs/Python/Python313/math module.py", line 103, in <module>
    print('current time:',dt.strftime('%H:/%M:/%S'))
NameError: name 'dt' is not defined

==== RESTART: C:/Users/asnat/AppData/Local/Programs/Python/Python313/math module.py ====
46
45
remainder value is" 1.0
GCD is: 12
Traceback (most recent call last):
  File "C:/Users/asnat/AppData/Local/Programs/Python/Python313/math module.py", line 103, in <module>
    print('current time:',dt.strftime('%H:/%M:/%S'))
NameError: name 'dt' is not defined

==== RESTART: C:/Users/asnat/AppData/Local/Programs/Python/Python313/math module.py ====
46
45
remainder value is" 1.0
GCD is: 12
Traceback (most recent call last):
  File "C:/Users/asnat/AppData/Local/Programs/Python/Python313/math module.py", line 104, in <module>
    print('current time:',dt.strftime('%H:/%M:/%S'))
NameError: name 'dt' is not defined

==== RESTART: C:/Users/asnat/AppData/Local/Programs/Python/Python313/math module.py ====
46
45
remainder value is" 1.0
GCD is: 12
Traceback (most recent call last):
  File "C:/Users/asnat/AppData/Local/Programs/Python/Python313/math module.py", line 104, in <module>
    print('current time:',dt.strftime('%H:/%M:/%S'))
AttributeError: module 'datetime' has no attribute 'strftime'

==== RESTART: C:/Users/asnat/AppData/Local/Programs/Python/Python313/math module.py ====
46
45
remainder value is" 1.0
GCD is: 12
2025-05-21 12:24:26.810608
2025-05-21
Traceback (most recent call last):
  File "C:/Users/asnat/AppData/Local/Programs/Python/Python313/math module.py", line 104, in <module>
    print('current time:',dt.strftime('%H:/%M:/%S'))
AttributeError: module 'datetime' has no attribute 'strftime'

==== RESTART: C:/Users/asnat/AppData/Local/Programs/Python/Python313/math module.py ====
46
45
remainder value is" 1.0
GCD is: 12
2025-05-21 12:24:39.995020
2025-05-21
Traceback (most recent call last):
  File "C:/Users/asnat/AppData/Local/Programs/Python/Python313/math module.py", line 103, in <module>
    print('current time:',dt.strftime('%H:/%M:/%S'))
AttributeError: module 'datetime' has no attribute 'strftime'

==== RESTART: C:/Users/asnat/AppData/Local/Programs/Python/Python313/math module.py ====
46
45
remainder value is" 1.0
GCD is: 12
2025-05-21 12:25:20.248667
2025-05-21
Traceback (most recent call last):
  File "C:/Users/asnat/AppData/Local/Programs/Python/Python313/math module.py", line 103, in <module>
    print('current time:',dt.strftime('%H:%M:%S'))
AttributeError: module 'datetime' has no attribute 'strftime'

==== RESTART: C:/Users/asnat/AppData/Local/Programs/Python/Python313/math module.py ====
46
45
remainder value is" 1.0
GCD is: 12
2025-05-21 12:26:54.827664
2025-05-21
Traceback (most recent call last):
  File "C:/Users/asnat/AppData/Local/Programs/Python/Python313/math module.py", line 103, in <module>
    print('current time:',dt.strftime('%H:%M:%S'))
AttributeError: module 'datetime' has no attribute 'strftime'

==== RESTART: C:/Users/asnat/AppData/Local/Programs/Python/Python313/math module.py ====
46
45
remainder value is" 1.0
GCD is: 12
2025-05-21 12:28:17.456643
2025-05-21
Traceback (most recent call last):
  File "C:/Users/asnat/AppData/Local/Programs/Python/Python313/math module.py", line 104, in <module>
    print('current time:',dt.strftime('%H:%M:%S'))
AttributeError: module 'datetime' has no attribute 'strftime'

==== RESTART: C:/Users/asnat/AppData/Local/Programs/Python/Python313/math module.py ====
46
45
remainder value is" 1.0
GCD is: 12
2025-05-21 12:30:22.476048
2025-05-21
Traceback (most recent call last):
  File "C:/Users/asnat/AppData/Local/Programs/Python/Python313/math module.py", line 105, in <module>
    print('current time:',dt.strftime('%H:%M:%S'))
AttributeError: module 'datetime' has no attribute 'strftime'

==== RESTART: C:/Users/asnat/AppData/Local/Programs/Python/Python313/math module.py ====
46
45
remainder value is" 1.0
GCD is: 12
2025-05-21 12:30:39.326555
2025-05-21
Traceback (most recent call last):
  File "C:/Users/asnat/AppData/Local/Programs/Python/Python313/math module.py", line 104, in <module>
    print('current time:',dt.strftime('%H:%M:%S'))
AttributeError: module 'datetime' has no attribute 'strftime'

==== RESTART: C:/Users/asnat/AppData/Local/Programs/Python/Python313/math module.py ====
46
45
remainder value is" 1.0
GCD is: 12
2025-05-21 12:33:06.020249
2025-05-21
current time: 12:33:06
Traceback (most recent call last):
  File "C:/Users/asnat/AppData/Local/Programs/Python/Python313/math module.py", line 106, in <module>
    print('current time:',dt.strftime('%h:%m:%s'))
ValueError: Invalid format string

==== RESTART: C:/Users/asnat/AppData/Local/Programs/Python/Python313/math module.py ====
46
45
remainder value is" 1.0
GCD is: 12
2025-05-21 12:36:20.472989
2025-05-21
current time: 12:36:20
current time: May:Wednesday:2025

==== RESTART: C:/Users/asnat/AppData/Local/Programs/Python/Python313/math module.py ====
46
45
remainder value is" 1.0
GCD is: 12
2025-05-21 12:37:07.073864
2025-05-21
current time: 12:37:07
current time: May:May:25
current time: May:Wednesday:2025

==== RESTART: C:/Users/asnat/AppData/Local/Programs/Python/Python313/math module.py ====
46
45
remainder value is" 1.0
GCD is: 12
2025-05-21 12:43:52.113881
2025-05-21
current time: 12:43:52
current time: May:May:25
current time: May:Wednesday:2025
Traceback (most recent call last):
  File "C:/Users/asnat/AppData/Local/Programs/Python/Python313/math module.py", line 110, in <module>
    dt=date(y,m,d)
NameError: name 'y' is not defined

==== RESTART: C:/Users/asnat/AppData/Local/Programs/Python/Python313/math module.py ====
46
45
remainder value is" 1.0
GCD is: 12
2025-05-21 12:44:58.757309
2025-05-21
current time: 12:44:58
current time: May:May:25
current time: May:Wednesday:2025
Traceback (most recent call last):
  File "C:/Users/asnat/AppData/Local/Programs/Python/Python313/math module.py", line 110, in <module>
    dt=date(y,m,d)
NameError: name 'y' is not defined

==== RESTART: C:/Users/asnat/AppData/Local/Programs/Python/Python313/math module.py ====
46
45
remainder value is" 1.0
GCD is: 12
2025-05-21 12:45:10.725251
2025-05-21
current time: 12:45:10
current time: May:May:25
current time: May:Wednesday:2025
Traceback (most recent call last):
  File "C:/Users/asnat/AppData/Local/Programs/Python/Python313/math module.py", line 110, in <module>
    dt=date(y,m,d)
NameError: name 'y' is not defined

==== RESTART: C:/Users/asnat/AppData/Local/Programs/Python/Python313/math module.py ====
46
45
remainder value is" 1.0
GCD is: 12
2025-05-21 12:46:00.658051
2025-05-21
current time: 12:46:00
current time: May:May:25
current time: May:Wednesday:2025
enter the date=23
Traceback (most recent call last):
  File "C:/Users/asnat/AppData/Local/Programs/Python/Python313/math module.py", line 109, in <module>
    d,m,y=[int(x)for x in input('enter the date=').split('/')]
ValueError: not enough values to unpack (expected 3, got 1)

==== RESTART: C:/Users/asnat/AppData/Local/Programs/Python/Python313/math module.py ====
46
45
remainder value is" 1.0
GCD is: 12
2025-05-21 12:46:15.395584
2025-05-21
current time: 12:46:15
current time: May:May:25
current time: May:Wednesday:2025
enter the date=23/3/2023
day 4 of the week,this isThursday
>>> 
=== RESTART: C:/Users/asnat/AppData/Local/Programs/Python/Python313/random module.py ===
0.9621127800316034
>>> 
=== RESTART: C:/Users/asnat/AppData/Local/Programs/Python/Python313/random module.py ===
0.09376154510067158
0.1456692551041303
>>> 
=== RESTART: C:/Users/asnat/AppData/Local/Programs/Python/Python313/random module.py ===
0.1456692551041303
>>> 
=== RESTART: C:/Users/asnat/AppData/Local/Programs/Python/Python313/random module.py ===
60
>>> 
=== RESTART: C:/Users/asnat/AppData/Local/Programs/Python/Python313/random module.py ===
52
>>> 
=== RESTART: C:/Users/asnat/AppData/Local/Programs/Python/Python313/random module.py ===
Traceback (most recent call last):
  File "C:/Users/asnat/AppData/Local/Programs/Python/Python313/random module.py", line 20, in <module>
    print(randint(5,25))
NameError: name 'randint' is not defined
>>> 
=== RESTART: C:/Users/asnat/AppData/Local/Programs/Python/Python313/random module.py ===
68
6
>>> 
=== RESTART: C:/Users/asnat/AppData/Local/Programs/Python/Python313/random module.py ===
58
5
>>> 
=== RESTART: C:/Users/asnat/AppData/Local/Programs/Python/Python313/random module.py ===
26
4
>>> 
=== RESTART: C:/Users/asnat/AppData/Local/Programs/Python/Python313/random module.py ===
67
4
59.05057763433384
